name: Build EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Codigo
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Compilar EXE com PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --collect-all customtkinter --name "ComparadorSegurados" "app.py"
        
    - name: Upload do Executavel
      uses: actions/upload-artifact@v4
      with:
        name: ComparadorSegurados-Windows
        path: dist/ComparadorSegurados.exe
